import { buildOwnerReportModel, toothLayName } from './ownerReport';
import { ChartSnapshot, EMPTY_EXAM_FINDINGS, EMPTY_NERVE_BLOCKS } from '../types';
import { getInitialToothData } from '../constants';

function baseSnapshot(): ChartSnapshot {
  return {
    patientInfo: {
      patientName: 'Biscuit',
      patientNumber: '42',
      ownerName: 'Sam Doe',
      ownerPhone: '',
      ownerEmail: '',
      doctor: '',
      tech: '',
      date: '2026-07-19',
      complaint: '',
      treatmentReport: '',
      recallDate: '2027-01-19',
      nerveBlocks: { ...EMPTY_NERVE_BLOCKS },
      exam: { ...EMPTY_EXAM_FINDINGS },
    },
    toothData: getInitialToothData('feline'),
    species: 'feline',
    logo: 'socal',
    preMarks: {},
    preComments: [],
    preStrokes: [],
    postMarks: {},
    postComments: [],
    postStrokes: [],
  };
}

test('toothLayName translates Triadan positions', () => {
  expect(toothLayName(104)).toBe('Upper right canine tooth (104)');
  expect(toothLayName(309)).toBe('Lower left first molar (309)');
  expect(toothLayName(202)).toBe('Upper left second incisor (202)');
  expect(toothLayName(504)).toBe('Baby upper right canine tooth (504)');
});

test('teeth with no findings are omitted; charted findings translate to lay language', () => {
  const snapshot = baseSnapshot();
  const tooth104 = snapshot.toothData.find((t) => t.triadan === 104)!;
  tooth104.pocket = '6';
  tooth104.mobility = 'M2';

  const model = buildOwnerReportModel(snapshot);
  expect(model.teeth).toHaveLength(1);
  expect(model.teeth[0].layName).toBe('Upper right canine tooth (104)');
  expect(model.teeth[0].notes).toEqual([
    'loose tooth (mobility M2)',
    'deepened gum pocket (6 mm)',
  ]);
});

test('extractions, pre-missing teeth, and anchored comments land in the model', () => {
  const snapshot = baseSnapshot();
  snapshot.preMarks = { 103: 'missing' };
  snapshot.postMarks = { 104: 'extracted' };
  snapshot.postComments = [
    { id: 'c1', text: 'Complicated crown fracture', anchorTriadan: 104 },
  ];

  const model = buildOwnerReportModel(snapshot);
  expect(model.alreadyMissing).toEqual(['Upper right third incisor (103)']);
  expect(model.extracted).toEqual(['Upper right canine tooth (104)']);
  const tooth104 = model.teeth.find((t) => t.triadan === 104)!;
  expect(tooth104.extracted).toBe(true);
  expect(tooth104.notes).toContain('Complicated crown fracture');
});

test('report blocks are generated by default and hand-edits win', () => {
  const generated = buildOwnerReportModel(baseSnapshot());
  expect(generated.intro).toContain('Biscuit had a professional dental assessment');
  expect(generated.homecareTips).toHaveLength(3);
  expect(generated.extraNotes).toBe('');

  const snapshot = baseSnapshot();
  snapshot.ownerReport = {
    intro: 'Custom opening.',
    homecare: 'Brush daily.\n\nUse VOHC chews.',
    extraNotes: 'Recheck the left canine in two weeks.',
  };
  const edited = buildOwnerReportModel(snapshot);
  expect(edited.intro).toBe('Custom opening.');
  expect(edited.homecareTips).toEqual(['Brush daily.', 'Use VOHC chews.']);
  expect(edited.extraNotes).toBe('Recheck the left canine in two weeks.');
});

test('abnormal exam areas surface with their labels', () => {
  const snapshot = baseSnapshot();
  snapshot.patientInfo.exam = {
    ...EMPTY_EXAM_FINDINGS,
    tongue: { status: 'abnormal', comment: 'Small ulcer, left side' },
  };

  const model = buildOwnerReportModel(snapshot);
  expect(model.examNotes).toEqual([{ area: 'Tongue', comment: 'Small ulcer, left side' }]);
  expect(model.recallDate).toBe('2027-01-19');
});
